services:
  
  gateway:
    container_name: gateway
    hostname: gateway
    build: ./build
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - data:/var/www/html
      - geoip:/etc/geoip # mount your maxmind geoip db here
    healthcheck:
      test: ["CMD", "curl http://localhost:80/health || exit 1"]
      timeout: 10s
    labels:
      - application.group=gateway
    networks:
      - gateway

volumes:
  certs:
  data:
  geoip:

networks:
  gateway:
