services:
  
  openresty:
    container_name: openresty
    hostname: openresty
    build: ./build
    restart: unless-stopped
    environment:
      ENV_VARIABLE: Hello from Env
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./conf/example.com.conf:/etc/nginx/conf.d/http/example.com.conf:ro
      - ./conf/includes/global.conf:/etc/nginx/includes/global.conf:ro
      - ./conf/lua:/etc/nginx/lua:ro
      - ./conf/html:/var/www/html
      - geoip:/etc/geoip # mount your maxmind geoip db here
    healthcheck:
      test: ["CMD", "curl http://localhost:80/health || exit 1"]
      timeout: 10s
    labels:
      - application.group=gateway
    networks:
      - gateway

volumes:
  geoip:

networks:
  gateway:
