services:
  
  gateway:
    container_name: gateway
    hostname: gateway
    build: ./build
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl http://localhost:80/health || exit 1"]
      timeout: 10s
    environment:
      ENV_VARIABLE: Hello from Env
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config/example.com.conf:/opt/openresty/nginx/conf/vhosts/http/example.com.conf:ro
      - ./config/includes/global.conf:/opt/openresty/nginx/conf/includes/global.conf:ro
      - ./config/lua:/opt/openresty/lualib/custom:ro
      - ./config/html:/var/www/html
      - geoip:/etc/geoip # mount your maxmind geoip db here (must be nonroot)
    labels:
      - application.group=gateway
    user: root
    read_only: true
    tmpfs:
      - /var/run/nginx
      - /etc/ssl/gateway
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE
      - CHOWN
      - SETUID
      - SETGID
    security_opt:
      - no-new-privileges:true
    networks:
      - gateway

volumes:
  geoip:

networks:
  gateway:
